In [1]:
import pandas as pd

In [4]:
arima_predictions = pd.read_csv('test_data.csv')

In [5]:
arima_predictions

,Data,ES080E,ES1000E,ES100E,ES1200E,ES125E,ES150E,ES200E,ES200E/16,ES250E,...,XS500E/16,XS600E,XS600E/16,XS700E,XS700E/16,XS800E,XS900E,Cena rudy żelaza,Stan epidemii w Polsce,Inflacja
0,2021-07-12,8,0,52,0,0,48,8,0,10,...,0,0,0,0,0,0,0,216.03,1,105.1
1,2021-07-19,66,0,192,0,0,66,110,6,0,...,0,0,0,0,0,0,0,211.99,1,105.1
2,2021-07-26,222,0,66,0,6,260,98,0,16,...,0,0,0,0,0,0,0,172.01,1,105.1
3,2021-08-02,0,0,6,0,0,96,0,0,20,...,0,0,0,0,0,0,0,167.95,1,105.1
4,2021-08-09,20,0,18,0,0,28,0,0,0,...,0,2,0,0,0,0,0,160.54,1,105.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,2023-01-02,0,0,0,0,0,10,4,0,0,...,0,0,0,0,0,0,0,122.33,0,116.6
78,2023-01-09,18,0,44,0,4,28,30,0,0,...,0,0,0,0,0,0,0,122.16,0,116.6
79,2023-01-16,36,0,24,0,0,4,16,0,0,...,0,0,0,0,0,0,0,122.70,0,116.6
80,2023-01-23,14,0,28,0,8,14,34,0,2,...,0,0,0,0,0,0,0,125.26,0,116.6
81,2023-01-30,16,0,28,0,0,54,56,6,4,...,0,0,0,0,0,0,0,125.14,0,116.6

In [9]:
arima_predictions.set_index('Data', inplace = True)

In [7]:
arima_predictions.drop(['Cena rudy żelaza', 'Stan epidemii w Polsce', 'Inflacja'], axis = 'columns', inplace = True)

In [10]:
arima_predictions

,ES080E,ES1000E,ES100E,ES1200E,ES125E,ES150E,ES200E,ES200E/16,ES250E,ES250E/16,...,XS450E,XS450E/16,XS500E,XS500E/16,XS600E,XS600E/16,XS700E,XS700E/16,XS800E,XS900E
Data,,,,,,,,,,,,,,,,,,,,,
2021-07-12,8,0,52,0,0,48,8,0,10,30,...,0,0,0,0,0,0,0,0,0,0
2021-07-19,66,0,192,0,0,66,110,6,0,4,...,0,0,8,0,0,0,0,0,0,0
2021-07-26,222,0,66,0,6,260,98,0,16,2,...,2,0,0,0,0,0,0,0,0,0
2021-08-02,0,0,6,0,0,96,0,0,20,0,...,0,0,0,0,0,0,0,0,0,0
2021-08-09,20,0,18,0,0,28,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-02,0,0,0,0,0,10,4,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2023-01-09,18,0,44,0,4,28,30,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2023-01-16,36,0,24,0,0,4,16,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2023-01-23,14,0,28,0,8,14,34,0,2,0,...,0,0,2,0,0,0,0,0,0,0
2023-01-30,16,0,28,0,0,54,56,6,4,0,...,0,0,2,0,0,0,0,0,0,0

In [14]:
products = arima_predictions.columns[0:1262]

In [15]:
products

Index(['ES080E', 'ES1000E', 'ES100E', 'ES1200E', 'ES125E', 'ES150E', 'ES200E',
       'ES200E/16', 'ES250E', 'ES250E/16',
       ...
       'XS450E', 'XS450E/16', 'XS500E', 'XS500E/16', 'XS600E', 'XS600E/16',
       'XS700E', 'XS700E/16', 'XS800E', 'XS900E'],
      dtype='object', length=1262)

In [19]:
arima_predictions[products] = arima_predictions[products].apply(lambda x: x*0)

In [20]:
arima_predictions

,ES080E,ES1000E,ES100E,ES1200E,ES125E,ES150E,ES200E,ES200E/16,ES250E,ES250E/16,...,XS450E,XS450E/16,XS500E,XS500E/16,XS600E,XS600E/16,XS700E,XS700E/16,XS800E,XS900E
Data,,,,,,,,,,,,,,,,,,,,,
2021-07-12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2021-07-19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2021-07-26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2021-08-02,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2021-08-09,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-02,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2023-01-09,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2023-01-16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2023-01-23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2023-01-30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
arima_predictions.to_csv('arima_results.csv')
arima_predictions.to_csv('nbeats_results.csv')
arima_predictions.to_csv('prophet_results.csv')