In [42]:
import pandas as pd
from sklearn.metrics import mean_absolute_error
import numpy as np

# Data import

In [9]:
arima_results = pd.read_csv('arima_results.csv', index_col = 0)

In [10]:
arima_results

,ES080E,ES1000E,ES100E,ES1200E,ES125E,ES150E,ES200E,ES200E/16,ES250E,ES250E/16,...,XS450E,XS450E/16,XS500E,XS500E/16,XS600E,XS600E/16,XS700E,XS700E/16,XS800E,XS900E
Data,,,,,,,,,,,,,,,,,,,,,
2021-07-12,37.556789,0.166717,60.484809,0.0,2.244648,89.893201,20.289692,2.58104,7.626594,11.289420,...,0.073394,0.0,0.65914,0.397183,0.501529,0.103976,0.091743,0.036697,0.17737,0.030581
2021-07-19,40.780350,0.136906,82.574173,0.0,2.244648,88.485169,27.288452,2.58104,29.141556,9.451585,...,0.073394,0.0,0.65914,0.102112,0.501529,0.103976,0.091743,0.036697,0.17737,0.030581
2021-07-26,35.565967,0.112819,78.067708,0.0,2.244648,94.128636,20.983573,2.58104,15.613123,7.147641,...,0.073394,0.0,0.65914,0.361217,0.501529,0.103976,0.091743,0.036697,0.17737,0.030581
2021-08-02,39.231446,0.107375,75.557430,0.0,2.244648,59.128465,36.150139,2.58104,8.262981,5.246769,...,0.073394,0.0,0.65914,0.128100,0.501529,0.103976,0.091743,0.036697,0.17737,0.030581
2021-08-09,47.080024,0.121951,75.833749,0.0,2.244648,99.858024,24.063437,2.58104,8.443245,4.320006,...,0.073394,0.0,0.65914,0.337836,0.501529,0.103976,0.091743,0.036697,0.17737,0.030581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-02,41.359331,0.142342,76.068053,0.0,2.244648,77.975805,25.297920,2.58104,8.929625,7.074863,...,0.073394,0.0,0.65914,0.238460,0.501529,0.103976,0.091743,0.036697,0.17737,0.030581
2023-01-09,41.359331,0.143125,76.068053,0.0,2.244648,84.172103,25.297920,2.58104,8.929625,7.075664,...,0.073394,0.0,0.65914,0.238544,0.501529,0.103976,0.091743,0.036697,0.17737,0.030581
2023-01-16,41.359331,0.143445,76.068053,0.0,2.244648,79.387784,25.297920,2.58104,8.929625,7.076532,...,0.073394,0.0,0.65914,0.238469,0.501529,0.103976,0.091743,0.036697,0.17737,0.030581
2023-01-23,41.359331,0.143166,76.068053,0.0,2.244648,82.490835,25.297920,2.58104,8.929625,7.077159,...,0.073394,0.0,0.65914,0.238537,0.501529,0.103976,0.091743,0.036697,0.17737,0.030581
2023-01-30,41.359331,0.142495,76.068053,0.0,2.244648,81.213287,25.297920,2.58104,8.929625,7.077378,...,0.073394,0.0,0.65914,0.238475,0.501529,0.103976,0.091743,0.036697,0.17737,0.030581

In [19]:
test_data = pd.read_csv('test_data.csv', index_col = 0)

In [20]:
test_data

,ES080E,ES1000E,ES100E,ES1200E,ES125E,ES150E,ES200E,ES200E/16,ES250E,ES250E/16,...,XS500E/16,XS600E,XS600E/16,XS700E,XS700E/16,XS800E,XS900E,Cena rudy żelaza,Stan epidemii w Polsce,Inflacja
Data,,,,,,,,,,,,,,,,,,,,,
2021-07-12,8,0,52,0,0,48,8,0,10,30,...,0,0,0,0,0,0,0,216.03,1,105.1
2021-07-19,66,0,192,0,0,66,110,6,0,4,...,0,0,0,0,0,0,0,211.99,1,105.1
2021-07-26,222,0,66,0,6,260,98,0,16,2,...,0,0,0,0,0,0,0,172.01,1,105.1
2021-08-02,0,0,6,0,0,96,0,0,20,0,...,0,0,0,0,0,0,0,167.95,1,105.1
2021-08-09,20,0,18,0,0,28,0,0,0,0,...,0,2,0,0,0,0,0,160.54,1,105.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-02,0,0,0,0,0,10,4,0,0,0,...,0,0,0,0,0,0,0,122.33,0,116.6
2023-01-09,18,0,44,0,4,28,30,0,0,0,...,0,0,0,0,0,0,0,122.16,0,116.6
2023-01-16,36,0,24,0,0,4,16,0,0,0,...,0,0,0,0,0,0,0,122.70,0,116.6
2023-01-23,14,0,28,0,8,14,34,0,2,0,...,0,0,0,0,0,0,0,125.26,0,116.6
2023-01-30,16,0,28,0,0,54,56,6,4,0,...,0,0,0,0,0,0,0,125.14,0,116.6

# Creating dataframe for results of MAE metric

In [23]:
products = test_data.columns[0:1262]

In [24]:
products

Index(['ES080E', 'ES1000E', 'ES100E', 'ES1200E', 'ES125E', 'ES150E', 'ES200E',
       'ES200E/16', 'ES250E', 'ES250E/16',
       ...
       'XS450E', 'XS450E/16', 'XS500E', 'XS500E/16', 'XS600E', 'XS600E/16',
       'XS700E', 'XS700E/16', 'XS800E', 'XS900E'],
      dtype='object', length=1262)

In [25]:
results = pd.DataFrame(index = products)

In [29]:
results["AutoARIMA"] = 0
results["N-BEATS"] = 0
results["Prophet"] = 0

In [30]:
results

           AutoARIMA  N-BEATS  Prophet
ES080E             0        0        0
ES1000E            0        0        0
ES100E             0        0        0
ES1200E            0        0        0
ES125E             0        0        0
...              ...      ...      ...
XS600E/16          0        0        0
XS700E             0        0        0
XS700E/16          0        0        0
XS800E             0        0        0
XS900E             0        0        0

[1262 rows x 3 columns]

# Processing ARIMA results

In [11]:
type(arima_results.iloc[0,0])

numpy.float64

In [12]:
arima_results = arima_results.applymap(lambda x: round(x))

In [13]:
arima_results

,ES080E,ES1000E,ES100E,ES1200E,ES125E,ES150E,ES200E,ES200E/16,ES250E,ES250E/16,...,XS450E,XS450E/16,XS500E,XS500E/16,XS600E,XS600E/16,XS700E,XS700E/16,XS800E,XS900E
Data,,,,,,,,,,,,,,,,,,,,,
2021-07-12,38,0,60,0,2,90,20,3,8,11,...,0,0,1,0,1,0,0,0,0,0
2021-07-19,41,0,83,0,2,88,27,3,29,9,...,0,0,1,0,1,0,0,0,0,0
2021-07-26,36,0,78,0,2,94,21,3,16,7,...,0,0,1,0,1,0,0,0,0,0
2021-08-02,39,0,76,0,2,59,36,3,8,5,...,0,0,1,0,1,0,0,0,0,0
2021-08-09,47,0,76,0,2,100,24,3,8,4,...,0,0,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-02,41,0,76,0,2,78,25,3,9,7,...,0,0,1,0,1,0,0,0,0,0
2023-01-09,41,0,76,0,2,84,25,3,9,7,...,0,0,1,0,1,0,0,0,0,0
2023-01-16,41,0,76,0,2,79,25,3,9,7,...,0,0,1,0,1,0,0,0,0,0
2023-01-23,41,0,76,0,2,82,25,3,9,7,...,0,0,1,0,1,0,0,0,0,0
2023-01-30,41,0,76,0,2,81,25,3,9,7,...,0,0,1,0,1,0,0,0,0,0

In [45]:
mae = []
for product in products:
    y_pred = np.array(arima_results[product])
    y_true = np.array(test_data[product])
    metric = mean_absolute_error(y_true, y_pred)
    mae.append(metric)

results['AutoARIMA'] = mae
results.to_csv('mae_results.csv')

In [47]:
type(results.iloc[0,0])

numpy.float64

In [48]:
results = results.applymap(lambda x: round(x))

In [49]:
results

           AutoARIMA  N-BEATS  Prophet
ES080E            37        0        0
ES1000E            0        0        0
ES100E            57        0        0
ES1200E            0        0        0
ES125E             6        0        0
...              ...      ...      ...
XS600E/16          0        0        0
XS700E             0        0        0
XS700E/16          0        0        0
XS800E             0        0        0
XS900E             0        0        0

[1262 rows x 3 columns]

In [50]:
results.to_csv('mae_results.csv')